#!/bin/sh
#
# crond       Starts crond
#

start() {
	printf "Starting crond:"
	/sbin/crond 
	touch /var/lock/crond
	echo "OK"
}
stop() {
	printf "Stopping crond:"
	killall crond
	rm -f /var/lock/crond
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

