#!/bin/sh
#
# httpd       Starts httpd
#

start() {
	printf "Starting httpd:"
	echo "### Starting httpd ###" >> /var/log/httpd.log
	/sbin/httpd -vv -h /var/www -c /etc/httpd.conf >> /var/log/httpd.log 2>&1
	touch /var/lock/httpd
	echo "OK"
}
stop() {
	printf "Stopping httpd:"
	echo "### Stopping httpd ###" >> /var/log/httpd.log
	killall httpd
	rm -f /var/lock/httpd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

